/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EndDigitalIndexRouteImport } from './routes/end-digital.index'
import { Route as RecursosIndexRouteImport } from './routes/recursos.index'
import { Route as RecursosSlugRouteImport } from './routes/recursos.$slug'
import { Route as RecursosCategoriaCategoriaRouteImport } from './routes/recursos.categoria.$categoria'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EndDigitalIndexRoute = EndDigitalIndexRouteImport.update({
  id: '/end-digital/',
  path: '/end-digital/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecursosIndexRoute = RecursosIndexRouteImport.update({
  id: '/recursos/',
  path: '/recursos/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecursosSlugRoute = RecursosSlugRouteImport.update({
  id: '/recursos/$slug',
  path: '/recursos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RecursosCategoriaCategoriaRoute =
  RecursosCategoriaCategoriaRouteImport.update({
    id: '/recursos/categoria/$categoria',
    path: '/recursos/categoria/$categoria',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/recursos/$slug': typeof RecursosSlugRoute
  '/end-digital/': typeof EndDigitalIndexRoute
  '/recursos/': typeof RecursosIndexRoute
  '/recursos/categoria/$categoria': typeof RecursosCategoriaCategoriaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/recursos/$slug': typeof RecursosSlugRoute
  '/end-digital': typeof EndDigitalIndexRoute
  '/recursos': typeof RecursosIndexRoute
  '/recursos/categoria/$categoria': typeof RecursosCategoriaCategoriaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/recursos/$slug': typeof RecursosSlugRoute
  '/end-digital/': typeof EndDigitalIndexRoute
  '/recursos/': typeof RecursosIndexRoute
  '/recursos/categoria/$categoria': typeof RecursosCategoriaCategoriaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/recursos/$slug'
    | '/end-digital/'
    | '/recursos/'
    | '/recursos/categoria/$categoria'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/recursos/$slug'
    | '/end-digital'
    | '/recursos'
    | '/recursos/categoria/$categoria'
  id:
    | '__root__'
    | '/'
    | '/recursos/$slug'
    | '/end-digital/'
    | '/recursos/'
    | '/recursos/categoria/$categoria'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RecursosSlugRoute: typeof RecursosSlugRoute
  EndDigitalIndexRoute: typeof EndDigitalIndexRoute
  RecursosIndexRoute: typeof RecursosIndexRoute
  RecursosCategoriaCategoriaRoute: typeof RecursosCategoriaCategoriaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/end-digital/': {
      id: '/end-digital/'
      path: '/end-digital'
      fullPath: '/end-digital/'
      preLoaderRoute: typeof EndDigitalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recursos/': {
      id: '/recursos/'
      path: '/recursos'
      fullPath: '/recursos/'
      preLoaderRoute: typeof RecursosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recursos/$slug': {
      id: '/recursos/$slug'
      path: '/recursos/$slug'
      fullPath: '/recursos/$slug'
      preLoaderRoute: typeof RecursosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recursos/categoria/$categoria': {
      id: '/recursos/categoria/$categoria'
      path: '/recursos/categoria/$categoria'
      fullPath: '/recursos/categoria/$categoria'
      preLoaderRoute: typeof RecursosCategoriaCategoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RecursosSlugRoute: RecursosSlugRoute,
  EndDigitalIndexRoute: EndDigitalIndexRoute,
  RecursosIndexRoute: RecursosIndexRoute,
  RecursosCategoriaCategoriaRoute: RecursosCategoriaCategoriaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
